# Generated by Django 4.2.3 on 2023-08-07 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_model',
            old_name='author',
            new_name='author_username',
        ),
    ]
